hyper:
    batch_size: 8
    gpu_ids: 0
    logs_dir: experiments/diff_crossattn
    results_dir: experiments/diff_crossattn
    name: ./
    isTrain: True
    device: 'cuda'
    distributed: 0
dataset:
    res: 64
    trunc_thres: 0.2
    ratio: 1

layout_branch:
    model: diffusion_scene_layout_ddpm
    denoiser: unet1d
    denoiser_kwargs:
        dim: 512
        dim_mults: [ 1, 1, 1, 1 ]
        channels: 65
        class_dim: 25
        angle_dim: 1
        relation_condition: true
        conditioning_key: crossattn
        crossattn_dim: 1280
        concat_dim: 0
        bbox_separate: true
        # self_condition: true
        # merge_bbox: true
        # modulate_time_context_instanclass: true
    diffusion_kwargs:
      schedule_type: 'linear'
      beta_start: 0.0001
      beta_end: 0.02
      time_num: 1000
      loss_type: 'mse'
      model_mean_type: 'eps'
      model_var_type: 'fixedsmall'
      loss_separate: true
      loss_iou: true
      iou_type: obb
      train_stats_file: /media/ymxlzgy/Data/Dataset/FRONT/boxes_centered_stats_all_trainval.txt

shape_branch:
    model: sdfusion-txt2shape
    ckpt: null
    df_cfg: ../config/sdfusion-txt2shape.yaml
    ddim_steps: 100
    ddim_eta: 0.0
    uc_scale: 3.0
    vq_model: vqvae
    vq_cfg: ../config/vqvae_snet.yaml
    vq_dset: None
    vq_cat: None
    vq_ckpt: ./checkpoint/vqvae_threedfront_best.pth
misc:
    debug: 0
    seed: 111
    backend: gloo
    local_rank: 0

training:
    lr: 1e-5
    lr_policy: lambda
    lr_decay_iters: 50
    lambda_L1: 10.0
